<?php
$memoria_descriptiva_de_seguridad = [
"INTRODUCCIÓN",
"GENERALIDADES" => ["OBJETIVOS"],
"DESCRIPCIÓN DEL SISTEMA ESTRUCTURAL",
"NORMATIVIDAD",
"EVALUACIÓN" => ["CÁLCULO DE AFORO", "COMPONENTES DEL PLAN", "DISTRIBUCIÓN ARQUITECTÓNICA", "DENSIDAD DE OCUPACIÓN DE LA EDIFICACIÓN", "CARACTERÍSTICAS DE LOS USUARIOS"],
"RUTAS DE EVACUACIÓN Y AFORO" => ["ANCHO LIBRE DE PUERTAS Y RAMPAS", "ANCHO LIBRE PARA PASAJES DE CIRCULACIÓN", "ANCHO LIBRE DE ESCALERAS"],
"CÁLCULO DE CAPACIDAD DE MEDIOS DE EVACUACIÓN" => ["CÁLCULO DE CAPACIDAD DE MEDIOS DE EVACUACIÓN"],
"INSTALACIONES DE SEGURIDAD" => ["DETECTORES DE HUMO Y TEMPERATURA", "SEÑALIZACIÓN DE RUTAS DE EVACUACIÓN", "ILUMINACIÓN DE RUTAS DE EVACACIÓN", "SEÑALIZACIÓN", "CRITERIOS PARA SEÑALIZACIÓN", "SEÑALIZACIÓN UTILIZADA"],
"SEÑALIZACIÓN PODOTÁCTIL",
"PLAN DE SEGURIDAD EN SITUACIONES DE EMERGENCIA" => [
"BASE LEGAL",
"OBJETIVOS",
"DESCRIPCIÓN DE LAS OPERACIONES",
"ORGANIZACIÓN DE LAS BRIGADAS" => ["COMITÉ DE SEGURIDAD", "BRIGADAS" => ["ESTRUCTURA TIPICAS DE UNA BRIGADA"], "FUNCIONES DE LAS BRIGADAS" => ["JEFE DE BRIGADAS", "SUB JEFE DE BRIGADAS", "BRIGADAS CONTRA INCENDIO", "BRIGADAS DE PRIMEROS AUXILIOS" => ["BRIGADAS DE EVACUACION"]], "PAUTAS PARA LAS BRIGADAS" => ["Responsables y Asistente Responsable"], "PAUTAS PARA EL PERSONAL QUE SE ENCUENTRE EN LA ZONA DE EMERGENCIA"], "EQUIPAMIENTO" => ["MÉTODOS DE PROTECCIÓN", "PLANOS DE SEGURIDAD DE LA INSTITUCIÓN EDUCATIVA"],
"LISTADO DE ELEMENTOS BASICOS DE DOTACION PARA EL BOTIQUIN DE PRIMEROS AUXILIOS",
"SISTEMAS DE COMUNICACIÓN DE EMERGENCIA",
"ACCIONES DE RESPUESTA FRENTE A:" => ["INCENDIOS" => ["Durante el incendio", "Después del incendio"],
"EN CASOS DE FUGAS", "CONSIDERACIONES ESPECIALES", "LLUVIAS INTENSAS", "SISMOS", "VIENTOS FUERTES"],
"ORGANISMO DE APOYO AL PLAN DE SEGURIDAD" => ["INCENDIOS", "EN CASOS DE FUGAS", "CONSIDERACIONES ESPECIALES", "LLUVIAS INTENSAS", "SISMOS", "VIENTOS FUERTES"],
"PROGRAMA DE CAPACITACIÓN DE LAS BRIGADAS" => ["PROCEDIMIENTO DE COORDINACIÓN ENTRE INSTITUCIONES Y/O VIVIENDAS DEL ENTORNO", "ENLACE CON LOS COMITÉS DE DEFENSA CIVIL DISTRITALES/PROVINCIALES, SEGÚN CORRESPONDA", "ENLACE CON EL CUERPO GENERAL DE BOMBEROS VOLUNTARIOS DEL PERÚ", "ENLACE CON LA POLICÍA NACIONAL DEL PERÚ", "ENLACE CON LOS SERVICIOS DE SALUD PÚBLICA Y PRIVADA"],
"PROGRAMA DE CAPACITACIONES DE LAS BRIGADAS"
]
];

$memoria_descriptiva_de_arquitectura = [
    "INTRODUCCIÓN" => ["ANTECEDENTES", "JUSTIFICACION DEL PROYECTO", "OBJETIVO DEL PROYECTO", "ALCANCES DE LA ESPECIALIDAD" ],
    "DATOS GENERALES DEL PROYECTO" => ["NOMBRE DEL PROYECTO", "NOMBRE DE LA UEI", "NOMBRE DE LA IE", ["UBICACION GEOGRAFICA" => ["Ubicacion Política", "Ubicacion Geografica coordenadas UTM", "Ubicacion Contextual"]], ["PARAMETROS CLIMATICOS",  "CARACTERÍSTICAS TÉCNICAS BIOCLIMÁTICAS: ZONA 4 (MESOANDINO)" ], ["NORMATIVA"]],
    "DATOS DE TERRENO ENTORNO" => ["DESCRIPPCION DEL TERRENO", "CONSIDERACIONES DEL TERRENO" => ["HABILITACION URBANA Y ZONIFICACION" =>["No corresponde por encontrarse dentro de una zona rural"], "PARAMETROS URBANISTICOS", "TIPOLOGIA DE TERRENO", "TIPOGRAFIA" =>["SUPERPOSICION DE POLIGONOS - AREA RESULTANTE", "VISTA DE LOS POLIGONOS CIRCUNSCRITOS TANTO DEL LEVANTAMIENTO TOPOGRAFICO Y SEGUN DOCUMENTOS DE REGISTROS PUBLICOS", "VISTA DEL POLIGONO RESULTANTE"], "DISPONIBILIDAD DE SERVICIOS BASICOS"=>["Agua", "Desagüe", "Energia Electrica"], "ANALISIS DEL ENTORNO" =>["EQUIPAMIENTO DEL ENTORNO", "MITIGACION DE RIESGOS Y PELIGROS DEL ENTORNO", "ESTUDIO DE SUELOS"]]],
    "METAS FISICAS DEL PROYECTO"=> ["RESULTADO DE LA DEMANDA"=>["PROYECCION DE LA DEMANDA EFECTIVA CON PROYECTO"], "DEMOLOCION"=>["DESCRIPCION DE ESTRUCTURAS EXISTENTES"=>["MODULO N° 01: Aulas 6° Grado de Primaria + Lavadero", "MODULO N° 02: Quiosco + Lavadero", "MODULO N° 03: Cocina, Despensa – Almacén + Lavadero", "MODULO N° 04: Aulas 1° y 5° secundaria, Almacén de educación física, Dirección, Biblioteca 50", "MODULO N° 05: SS.HH. +Lavadero", "MODULO N° 06: Aula de 1° y 5° de primaria", "MODULO N° 07: Tanque Elevado", "MODULO N° 08: Aula 2° secundaria", "MODULO N° 09: AULA  2°,3° Y 4° DE PRIMARIA", "MODULO N° 10: Aula 4° secundaria + Lavadero", "MODULO N° 11: Aula 3° secundaria", "MODULO N° 12: Torre Campana", "MODULO N° 13: SS. HH General + lavadero", "MODULO N°14: Casa abandonada"], "DESCRIPCIÓN DE OBRAS EXTERIORES/COMPLEMENTARIAS (CERCO PERIMÉTRICO, PATIOS, LOSAS DEPORTIVAS, VEREDAS, LAVADEROS, CIRCULACIÓN EXTERIOR, ETC.)."=>["Obra exterior N°1: Vereda de Concreto Simple", "Obra exterior N°2: Losa Deportiva", "Obra exterior N°3: Escalera de Concreto Simple", "Obra exterior N°4: Patio de Concreto Simple", "Obra exterior N°5: Cerco Perimétrico de Tapial", "Mobiliario Existente"], "OBRA NUEVA", "MOBILIARIO Y EQUIPAMIENTO"=>["CARACTERÍSTICAS TÉCNICAS DE LOS RECURSOS TIC"]]],
    "CONSIDERACIONES GENERALES DE DISEÑO"=>["PLANTEAMIENTO ARQUITECTONICO", "CONSIDERACIONES Y EMPLAZAMIENTO SEGÚN ZONA BIOCLIMATICA"=>["ANALISIS DE ASOLEAMIENTO , ORIENTACION.", "CUADRO DE CÁLCULO DE VENTILACION E ILUMINACION", "ANALISIS DE VARIABLE DE EMPLAZAMIENTO", "ANALISIS DE VARIABLE FUNCIONAL", "ANALISIS DE VARIABLE DE DISEÑO BIOCLIMATICO", "CUADRO DE ACABADOS"], "CONSIDERACIONES PEDAGOGICAS" => ["PROGRAMAS SOCIALES QUE RECIBE LA I.E.", "DISTRIBUCION DE HORAS SEMANALES" =>["POR NIVELES"], "PLANILLA DE PERSONAL DE LA IE", "CÁLCULO DE TIEMPO DE USO DE AMBIENTES"=>["POR AREA CURRICULAR PRIMARIA", "POR AREA CURRICULAR SECUNDARIA", "CUANTIFICACIÓN Y OPTIMIZACIÓN DE AMBIENTES"]]],
    "DESCRIPCION DE AMBIENTES" => ["SUSTENTO", "DIMENSIONAMIENTO DE AMBIENTES"],
    "RELACION DE DOCUMENTOS DEL PROYECTO",
    "RELACION DE PLANOS DEL PROYECTO",
];